#### Write this as a brief summary of your interests and intent, including:

* The kind of data you'd like to work with/field you're interested in (e.g., geodata, weather data, etc.)

* The kinds of questions you'll be asking of that data

* Possible source for such data

In other words, write down what kind of data you plan to work with, and what kinds of questions you'd like to ask of it. This constitutes your Project Proposal/Outline, and should look something like this:

> Our project is to uncover patterns in criminal activity around Los Angeles. We'll examine relationships between types of crime and location; crime rates and times of day; trends in crime rates over the course of the year; and related questions, as the data admits.

#### Finding Data

Once your group has written an outline, it's time to start hunting for data. You are free to use data from any source, but we recommend the following curated sources of high-quality data:

* [data.world](https://data.world/)

* [Kaggle](https://www.kaggle.com/)

* [Data.gov](https://www.data.gov)

* [Public APIs](https://github.com/abhishekbanthia/Public-APIs)

* [Awesome-APIs List](https://github.com/Kikobeats/awesome-api)

* [Medium APIs List](https://medium.com/@benjamin_libor/a-curated-collection-of-over-150-apis-to-build-great-products-fdcfa0f361bc)

Chances are you'll have to update your Project Outline as you explore the available data. **This is fine**â€”adjustments like this are part of the process! Just make sure everyone in the group is up-to-speed on the goals of the project as you make changes.

Make sure that your data is not too large for local analysis. **Big Data** datasets are difficult to manage locally, so consider a subset of that data or a different dataset altogether.

#### Data Cleanup & Analysis

With data in hand, it's time to tackle development and analysis. This is where the fun starts!

Inevitably, the analysis process can be broken into two broad phases: **Exploration & Cleanup** and **Analysis** proper.

As you've learned, you'll need to explore, clean, and reformat your data before you can begin to answer your research questions. We recommend keeping track of these exploration and cleanup steps in a dedicated Jupyter Notebook, both for organization's sake and to make it easier to  present your work later.

Similarly, after you've massaged your data and are ready to start crunching numbers, you should keep track of your work in a Jupyter Notebook dedicated specifically to analysis.

During both phases, **don't forget to include plots**! Don't make the mistake of waiting to build figures until you're preparing your presentation. Creating them along the way can reveal insights and interesting trends in the data that you might not notice otherwise.

We recommend focusing your analysis on techniques such as aggregation, correlation, comparison, summary statistics, sentiment analysis, and time series analysis.

Finally, be sure that your projects meet the [technical requirements](TechnicalRequirements.md).

In [8]:
import pandas as pd 


csv_path = "overdose_processed_states.csv"
StateOverdose_df = pd.read_csv(csv_path)

StateOverdose_df.head(10)

,State,Year,Deaths,Death_Rate,Pct_of_Total_Deaths,Multiple_Cause_of_death,log_of_Deaths,log_of_Pct_of_Deaths,log_of_Death_Rate
0,Wyoming,2000,NaN,NaN,NaN,Heroin,NaN,NaN,NaN
1,Wyoming,2000,NaN,NaN,NaN,Other opioids,NaN,NaN,NaN
2,Wyoming,2000,NaN,NaN,NaN,Methadone,NaN,NaN,NaN
3,Wyoming,2000,NaN,NaN,NaN,Other synthetic narcotics,NaN,NaN,NaN
4,Wyoming,2000,0.0,0.0,0.0,All Opioids,0.0,0.0,0.0
5,Wyoming,2001,NaN,NaN,NaN,Heroin,NaN,NaN,NaN
6,Wyoming,2001,NaN,NaN,NaN,Other opioids,NaN,NaN,NaN
7,Wyoming,2001,NaN,NaN,NaN,Methadone,NaN,NaN,NaN
8,Wyoming,2001,NaN,NaN,NaN,Other synthetic narcotics,NaN,NaN,NaN
9,Wyoming,2001,0.0,0.0,0.0,All Opioids,0.0,0.0,0.0

In [10]:
StateOverdose_df = StateOverdose_df.dropna(how="any")
StateOverdose_df.head(10)

,State,Year,Deaths,Death_Rate,Pct_of_Total_Deaths,Multiple_Cause_of_death,log_of_Deaths,log_of_Pct_of_Deaths,log_of_Death_Rate
4,Wyoming,2000,0.0,0.0,0.0,All Opioids,0.000000,0.0,0.000000
9,Wyoming,2001,0.0,0.0,0.0,All Opioids,0.000000,0.0,0.000000
14,Wyoming,2002,10.0,0.0,0.0,All Opioids,2.302585,0.0,0.000000
19,Wyoming,2003,0.0,0.0,0.0,All Opioids,0.000000,0.0,0.000000
24,Wyoming,2004,0.0,0.0,0.0,All Opioids,0.000000,0.0,0.000000
29,Wyoming,2005,0.0,0.0,0.0,All Opioids,0.000000,0.0,0.000000
34,Wyoming,2006,0.0,0.0,0.0,All Opioids,0.000000,0.0,0.000000
39,Wyoming,2007,0.0,0.0,0.0,All Opioids,0.000000,0.0,0.000000
41,Wyoming,2008,24.0,5.8,0.0,Other opioids,3.178054,0.0,1.757858
44,Wyoming,2008,35.0,5.8,0.0,All Opioids,3.555348,0.0,1.757858